"""add is_verified to recruiter_profiles

Revision ID: 01b1d6a76f10
Revises: 87af405ae2a4
Create Date: 2026-09-18 17:53:00.878711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b1d6a76f10'
down_revision: Union[str, Sequence[str], None] = '87af405ae2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruiter_profiles', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruiter_profiles', 'is_verified')
    # ### end Alembic commands ###
