"""create_project_evidence_table

Revision ID: 23d1824b3816
Revises: d4862ba643b7
Create Date: 2026-09-27 01:26:11.611846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d1824b3816'
down_revision: Union[str, Sequence[str], None] = 'd4862ba643b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('innovation_project_id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_type', sa.Enum('repository', 'document', 'image', 'video', 'demo', 'presentation', 'link', 'other', name='evidence_type', native_enum=False), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['innovation_project_id'], ['innovation_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['milestone_id'], ['project_milestones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_evidence_innovation_project_id'), 'project_evidence', ['innovation_project_id'], unique=False)
    op.create_index(op.f('ix_project_evidence_milestone_id'), 'project_evidence', ['milestone_id'], unique=False)
    op.create_index('ix_project_evidence_project_type', 'project_evidence', ['innovation_project_id', 'evidence_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_evidence_project_type', table_name='project_evidence')
    op.drop_index(op.f('ix_project_evidence_milestone_id'), table_name='project_evidence')
    op.drop_index(op.f('ix_project_evidence_innovation_project_id'), table_name='project_evidence')
    op.drop_table('project_evidence')
    # ### end Alembic commands ###
