"""create saved_jobs table

Revision ID: 87af405ae2a4
Revises: 952c21322497
Create Date: 2026-09-18 17:23:17.138205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87af405ae2a4'
down_revision: Union[str, Sequence[str], None] = '952c21322497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'job_posting_id', name='uq_saved_job_student_job')
    )
    op.create_index(op.f('ix_saved_jobs_job_posting_id'), 'saved_jobs', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_saved_jobs_student_id'), 'saved_jobs', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_jobs_student_id'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_job_posting_id'), table_name='saved_jobs')
    op.drop_table('saved_jobs')
    # ### end Alembic commands ###
