"""create job_postings table

Revision ID: a80f62ac6bac
Revises: 823b612d228b
Create Date: 2026-09-17 22:55:24.630541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80f62ac6bac'
down_revision: Union[str, Sequence[str], None] = '823b612d228b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('opportunity_type', sa.Enum('internship', 'job', name='opportunity_type', native_enum=False), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', name='employment_type', native_enum=False), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('minimum_qualification', sa.String(length=100), nullable=True),
    sa.Column('experience_required', sa.String(length=50), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_recruiter_id'), 'job_postings', ['recruiter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_postings_recruiter_id'), table_name='job_postings')
    op.drop_table('job_postings')
    # ### end Alembic commands ###
