"""align_enum_types_and_constraints

Revision ID: d4862ba643b7
Revises: e4c7b819f2a0
Create Date: 2026-09-26 23:03:33.789975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4862ba643b7'
down_revision: Union[str, Sequence[str], None] = 'e4c7b819f2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experience_records', 'experience_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('project', 'internship', 'work', 'research', 'leadership', 'certification', name='experience_type', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'work'::character varying"))
    op.alter_column('experience_records', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('draft', 'claimed', 'pending_verification', 'verified', 'rejected', name='verification_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'claimed'::character varying"))
    op.alter_column('experience_records', 'verification_source',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('self_claimed', 'platform_project', 'recruiter_confirmed', 'admin_confirmed', name='verification_source', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'self_claimed'::character varying"))
    op.alter_column('innovation_projects', 'project_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('software', 'hardware', 'research', 'academic', 'entrepreneurship', 'social_impact', 'other', name='project_type', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'software'::character varying"))
    op.alter_column('innovation_projects', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('draft', 'active', 'archived', name='project_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('innovation_projects', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('private', 'public', name='project_visibility', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'public'::character varying"))
    op.drop_constraint(op.f('uq_notification_preferences_user_id'), 'notification_preferences', type_='unique')
    op.alter_column('project_milestones', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('todo', 'in_progress', 'completed', name='milestone_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'todo'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_milestones', 'status',
               existing_type=sa.Enum('todo', 'in_progress', 'completed', name='milestone_status', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'todo'::character varying"))
    op.create_unique_constraint(op.f('uq_notification_preferences_user_id'), 'notification_preferences', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('innovation_projects', 'visibility',
               existing_type=sa.Enum('private', 'public', name='project_visibility', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'public'::character varying"))
    op.alter_column('innovation_projects', 'status',
               existing_type=sa.Enum('draft', 'active', 'archived', name='project_status', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('innovation_projects', 'project_type',
               existing_type=sa.Enum('software', 'hardware', 'research', 'academic', 'entrepreneurship', 'social_impact', 'other', name='project_type', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'software'::character varying"))
    op.alter_column('experience_records', 'verification_source',
               existing_type=sa.Enum('self_claimed', 'platform_project', 'recruiter_confirmed', 'admin_confirmed', name='verification_source', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'self_claimed'::character varying"))
    op.alter_column('experience_records', 'status',
               existing_type=sa.Enum('draft', 'claimed', 'pending_verification', 'verified', 'rejected', name='verification_status', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'claimed'::character varying"))
    op.alter_column('experience_records', 'experience_type',
               existing_type=sa.Enum('project', 'internship', 'work', 'research', 'leadership', 'certification', name='experience_type', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'work'::character varying"))
    # ### end Alembic commands ###
